name: assignment-test
on:
    push:
        tags-ignore:
            - '*'
        branches:
            - '*'
jobs:
      full-test:
        runs-on: self-hosted
        steps:
          - uses: actions/checkout@v3
            with:
              clean: false
              submodules: 'recursive'
          - name: Check if SSH_PRIVATE_KEY is set
            run: |
              if [ -z "${{ secrets.SSH_PRIVATE_KEY }}" ]; then
                echo "SSH_PRIVATE_KEY is empty!"
                exit 1
              else
                echo "SSH_PRIVATE_KEY is set."
              fi
          - uses: webfactory/ssh-agent@v0.5.4
            with:
                 ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          - name: List files
            run: ls -l ${GITHUB_WORKSPACE}
          - name: Run build
            timeout-minutes: 999999999999999999999
            run: |
               docker run --rm \
                 --privileged \
                 -v $SSH_AUTH_SOCK:/ssh-agent -e SSH_AUTH_SOCK=/ssh-agent \
                 -e GIT_SSH_COMMAND="ssh -o StrictHostKeyChecking=no" \
                 -v ${GITHUB_WORKSPACE}:${GITHUB_WORKSPACE} \
                 -v /var/run/docker.sock:/var/run/docker.sock \
                 cuaesd/aesd-autotest:24-assignment6-yocto \
                 --workdir=${GITHUB_WORKSPACE} \
                 ./build.sh
          - name: Cleanup
            if: always()
            run: |
              ssh-add -D
          - name: Run full test
            timeout-minutes: 15
            run: |
               docker run --rm \
                 -v ${GITHUB_WORKSPACE}:${GITHUB_WORKSPACE} \
                 cuaesd/aesd-autotest:assignment6-yocto \
                 --workdir=${GITHUB_WORKSPACE} \
                 ./full-test.sh
